import { DemoScenario } from '../types';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'scenario-1-inside',
    name: 'Scenario 1: Clearly Inside Zone',
    description: 'Observation well inside the Shivneri polygon with high-accuracy GPS (±4.5m).',
    category: 'POSSIBLE_CONSTRUCTION',
    factualNotes: 'Stone foundation excavation and mortar mixing observed 15m inside north gateway.',
    latitude: 19.1982,
    longitude: 73.8624,
    gpsAccuracyMeters: 4.5,
    expectedClassification: 'POTENTIAL_ZONE_CONCERN',
    demonstrates: 'Accurate spatial detection and formal evidence packet generation.',
  },
  {
    id: 'scenario-2-outside',
    name: 'Scenario 2: Clearly Outside Zone',
    description: 'Observation 180 meters outside the boundary with high GPS precision.',
    category: 'ALTERATION_OR_OBSTRUCTION',
    factualNotes: 'Commercial advertising board erected on approach road 200m from main gate.',
    latitude: 19.2085,
    longitude: 73.8750,
    gpsAccuracyMeters: 5.0,
    expectedClassification: 'NO_SPATIAL_CONCERN_INDICATED',
    demonstrates: 'System does not falsely flag activity outside protected boundaries.',
  },
  {
    id: 'scenario-3-near-boundary',
    name: 'Scenario 3: Near Boundary (Edge Uncertainty)',
    description: 'Point is 6 meters from boundary line with ±14.5m GPS accuracy (disk intersects boundary).',
    category: 'PHYSICAL_DAMAGE',
    factualNotes: 'Displaced masonry blocks noted near perimeter boundary stone.',
    latitude: 19.2020,
    longitude: 73.8660,
    gpsAccuracyMeters: 14.5,
    expectedClassification: 'LOCATION_UNCERTAIN',
    demonstrates: 'The core trust moment: system refuses to overclaim and flags uncertainty.',
  },
  {
    id: 'scenario-4-poor-gps',
    name: 'Scenario 4: Degraded GPS Signal',
    description: 'Deep canopy / gorge location reporting ±46m horizontal accuracy error (> 35m threshold).',
    category: 'DUMPING_OR_WASTE',
    factualNotes: 'Debris accumulated in rock crevice along base path.',
    latitude: 19.1982,
    longitude: 73.8624,
    gpsAccuracyMeters: 46.0,
    expectedClassification: 'EVIDENCE_INSUFFICIENT',
    demonstrates: 'Sensor error gatekeeper: prevents premature calculation from low-quality hardware data.',
  },
];
