/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "canvas-bg": "#f8fafc",
        "surface-card": "#ffffff",
        "surface-well": "#f1f5f9",
        "surface-dim": "#ccdbf3",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "border-subtle": "#e2e8f0",
        "border-strong": "#cbd5e1",
        "text-primary": "#0f172a",
        "text-secondary": "#475569",
        "text-muted": "#94a3b8",
        "primary": "#a33900",
        "primary-container": "#cc4900",
        "primary-surface": "#fff7ed",
        "primary-border": "#fed7aa",
        "primary-saffron": "#d95a00",
        "primary-fixed": "#ffdbce",
        "primary-fixed-dim": "#ffb599",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "secondary": "#006398",
        "secondary-surface": "#f0f7ff",
        "secondary-border": "#b8dcff",
        "secondary-container": "#5bb8fe",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#00476e",
        "tertiary": "#545c72",
        "tertiary-container": "#6c748b",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fefcff",
        "outline": "#8e7166",
        "outline-variant": "#e2bfb2",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "zone-core": "#dc2626",
        "zone-core-bg": "#fef2f2",
        "zone-core-border": "#fecaca",
        "zone-regulated": "#d97706",
        "zone-regulated-bg": "#fffbeb",
        "zone-regulated-border": "#fde68a",
        "zone-survey": "#059669",
        "zone-survey-bg": "#ecfdf5",
        "zone-survey-border": "#a7f3d0",
        "interactive-focus": "#ea580c",
        "slate-850": "#172033",
        sandstone: {
          50: '#fdfbf7',
          100: '#f7f1e6',
          200: '#ede0c8',
          300: '#dfc9a3',
          400: '#cdac7b',
          500: '#b88d55',
          600: '#9e7343',
          700: '#7f5936',
          800: '#67482f',
          900: '#563c29',
          950: '#301f14',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'code-telemetry': ['JetBrains Mono', 'monospace'],
        'code-dossier': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      boxShadow: {
        '2xs': '0 1px 1px 0 rgba(0, 0, 0, 0.03)',
        'xs': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      },
      dropShadow: {
        'xs': '0 1px 1px rgba(0, 0, 0, 0.05)',
      },
      backdropBlur: {
        'xs': '2px',
      },
      spacing: {
        '18': '4.5rem',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        zoomIn95: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        slideFromTop2: {
          '0%': { opacity: '0', transform: 'translateY(-0.5rem)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'fade-in': 'fadeIn 0.2s ease-out',
        'in': 'fadeIn 0.2s ease-out',
        'zoom-in-95': 'zoomIn95 0.2s ease-out',
        'slide-in-from-top-2': 'slideFromTop2 0.2s ease-out',
      },
    },
  },
  plugins: [],
};
