/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "canvas-bg": "#f8fafc",
        "surface-card": "#ffffff",
        "surface-well": "#f1f5f9",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d5e3fc",
        "border-subtle": "#e2e8f0",
        "border-strong": "#cbd5e1",
        "text-primary": "#0f172a",
        "text-secondary": "#475569",
        "text-muted": "#94a3b8",
        "primary": "#a33900",
        "primary-container": "#cc4900",
        "primary-saffron": "#d95a00",
        "primary-fixed": "#ffdbce",
        "primary-fixed-dim": "#ffb599",
        "on-primary": "#ffffff",
        "secondary": "#006398",
        "secondary-surface": "#f0f7ff",
        "secondary-border": "#b8dcff",
        "secondary-container": "#5bb8fe",
        "on-secondary": "#ffffff",
        "zone-core": "#dc2626",
        "zone-core-bg": "#fef2f2",
        "zone-core-border": "#fecaca",
        "zone-regulated": "#d97706",
        "zone-regulated-bg": "#fffbeb",
        "zone-regulated-border": "#fde68a",
        "zone-survey": "#059669",
        "zone-survey-bg": "#ecfdf5",
        "zone-survey-border": "#a7f3d0",
        "interactive-focus": "#ea580c",
        sandstone: {
          50: '#fdfbf7',
          100: '#f7f1e6',
          200: '#ede0c8',
          300: '#dfc9a3',
          400: '#cdac7b',
          500: '#b88d55',
          600: '#9e7343',
          700: '#7f5936',
          800: '#67482f',
          900: '#563c29',
          950: '#301f14',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'code-telemetry': ['JetBrains Mono', 'monospace'],
        'code-dossier': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
